namespace Elements.Battle.Core
{
    public enum PriorityPattern
    {
        None = 1,
        Random = 2,
        Near = 3,
        Far = 4,
        HpAsc = 5,
        HpDec = 6,
        Owner = 7,
        RandomOnce = 8,
        Forward = 9,
        Back = 10,
        AbsolutePosition = 11,
        EnergyDec = 12,
        EnergyAsc = 13,
        AtkDec = 14,
        AtkAsc = 15,
        MagicStrDec = 16,
        MagicStrAsc = 17,
        Summon = 18,
        EnergyReducing = 19,
        AtkPhysics = 20,
        AtkMagic = 21,
        AllSummonRandom = 22,
        OwnSummonRandom = 23,
        Boss = 24,
        HpAscNear = 25,
        HpDecNear = 26,
        EnergyDecNear = 27,
        EnergyAscNear = 28,
        AtkDecNear = 29,
        AtkAscNear = 30,
        MagicStrDecNear = 31,
        MagicStrAscNear = 32,
        Shadow = 33,
        NearMyTeamWithoutOwner = 34,
        HpValueDecNearForward = 35,
        HpValueAscNearForward = 36,
        EnergyDecNearMaxForward = 37,
        PhysicsOrMagicHighAttackDec = 38,
        PhysicsOrMagicHighAttackAsc = 39,
        AllEnemyIncludeStealth = 40,
        EnergyAscBackWithoutOwner = 41,
        ParentTargetParts = 42,
        AtkDecForwardWithoutOwner = 43,
        HpAscWithoutOwner = 44,
        AtkDefAscForward = 45,
        MagicDefAscForward = 46,
        FlightOnly = 47,
        NearWithoutTargetAbnormalState = 11000,
        FarWithoutTargetAbnormalState = 12000
    }
}