
namespace Elements
{
    public enum eColorGradation 
    {
        NONE = 0,
        EmphasisOrange = 1,
        Increment = 2,
        Decrement = 3,
        Alert = 4,
        RankFirst = 5,
        RankSecond = 6,
        RankThird = 7,
        RankFourth = 8,
        RankFifth = 9,
        RankSix = 10,
        RankSeventh = 11,
        RankEighth = 12,
        RankNinth = 13,
        RankTenth = 14,
        UnitLevel = 15,
        ArenaEmphasisBlue = 16,
        ArenaEmphasisGold = 17,
        ParamEmphasisGreen = 18,
        ParamEmphasisOrange = 19,
        ParamEmphasisRed = 20,
        TitleNavyBlue = 21,
        GachaTop = 22,
        GachaEndDatePickup = 23,
        GachaEndDateAnniversary = 24,
        GachaEndDateFestival = 25,
        GachaEndDatePrize = 26,
        TitlePurpleBlue = 27,
        TitlePurpleRed = 28,
        ClanBattleRankingTitleAll = 29,
        ClanBattleRankingTextAll = 30,
        ClanBattleRankingTitleIn = 31,
        ClanBattleRankingTextIn = 32,
        ClanBattleModeClan = 33,
        ClanBattleModeSingle = 34,
        TowerChallaengeFloor = 35,
        TowerNotChallaengeFloor = 36,
        RaceRank1 = 37,
        RaceRank2 = 38,
        RaceRank3 = 39,
        RaceRank4 = 40,
        ClanBattleScoreGold = 41,
        RoboLlamaDamageLog = 42,
        GlobalRaidRankingAllUser = 43,
        GlobalRaidRankingInClan = 44,
        UnitIconUniqueEquip1Level = 45,
        UnitIconUniqueEquip2Level = 46,
        CaravanTreasureSlotHighRarity = 47,
        ColosseumHighScore = 48,
        ColosseumResultScoreSilver = 49,
        ColosseumResultScoreGold = 50,
        TalentFormationBonusHigherDefault = 51,
        TalentFormationBonusLowerDefault = 52,
        TalentQuestFireAreaBossLabel = 53,
        TalentQuestWaterAreaBossLabel = 54,
        TalentQuestWindAreaBossLabel = 55,
        TalentQuestLightAreaBossLabel = 56,
        TalentQuestDarkAreaBossLabel = 57,
    }
}