public enum eParamType
{
	None = 0,
	Hp = 1,
	Atk = 2,
	Def = 3,
	MagicAtk = 4,
	MagicDef = 5,
	PhysicalCritical = 6,
	MagicCritical = 7,
	Dodge = 8,
	LifeSteal = 9,
	WaveHpRecovery = 10,
	WaveEnergyRecovery = 11,
	PhysicalPenetrate = 12,
	MagicPenetrate = 13,
	EnergyRecoveryRate = 14,
	HpRecoveryRate = 15,
	EnergyReduceRate = 16,
	Accuracy = 17,
	BaseParameterNum = 18,
	PhysicalCriticalDamageRate = 100,
	MagicCriticalDamageRate = 101,
	PhysicalDamageUpPercent = 102,
	MagicDamageUpPercent = 103,
	TalentBonus = 104,
	InvalidValue = -1,
}